### ISSUE TITLE
Broken Normals on some of the weapons

### ISSUE THREAD

**Issue by Nano975** [Wildenhaus/IndexV2#12]
Hey there, I've noticed that some of the weapons mesh normals appear to be broken.

![image](https://github.com/user-attachments/assets/51b0d87d-9281-4b3b-9b18-ac18335e3fdc)

Looks to be the case for a lot of the bolt weapons and combat knife, though the bolt pistol and the 4 other melee weapons are fine as far as I know.

Can be seen in Index as well
![image](https://github.com/user-attachments/assets/7b122088-174f-491d-9c30-64a931ccda4f)

There may be some that I haven't seen yet but the majority of bolt weapons have broken mesh normals.

**Comment by Wildenhaus** [comment]
Can you please replace GameProfiles/Index.Profiles.SpaceMarine2.dll with this one and let me know if it fixes the problem or if any other meshes have broken as a result?

[Index.Profiles.SpaceMarine2.zip](https://github.com/user-attachments/files/17124138/Index.Profiles.SpaceMarine2.zip)

**Comment by Nano975** [comment]
First look and the bolt rifle looks good.
![image](https://github.com/user-attachments/assets/16736ea8-ef71-4fd3-923f-9598b7a4c344)

Blender solid view shows a bit odd normals, but with the normal map applied they're fixed
![image](https://github.com/user-attachments/assets/175f4b65-52f4-4156-9684-30d2f1d5a26d)

![image](https://github.com/user-attachments/assets/aaa20b27-1666-4aa5-bcb8-eb7ac0713e2a)

But all the other weapons look good so far. Ill keep an eye out for any other problems

**Comment by Nano975** [comment]
I also forgot to mention that some of the particle texture sheets are broken as well. Though there are some that are completely fine
Examples:
![part_arifle_flame](https://github.com/user-attachments/assets/2e9a1d50-acde-4a6e-8154-336587d6a808)
![part_muzzle_front_01](https://github.com/user-attachments/assets/d5713ba1-9e2a-46d9-99f1-ad8e3d876dd5)
![part_muzzle_side_01](https://github.com/user-attachments/assets/14c47682-ffa8-4a47-9f87-e5c020c19e61)
![part_pyro_b](https://github.com/user-attachments/assets/f4cfe934-1bca-44d4-8209-989fa64a4514)
![part_q_expl_flash_01](https://github.com/user-attachments/assets/47c3cf2b-ecec-411c-9527-20e4d5170bf1)
![part_shells_01](https://github.com/user-attachments/assets/dca60c35-30f2-47c5-bdc6-27f24331eadb)

**Comment by Nano975** [comment]
On close inspection, the red channel looks fine but the green channel is pixelated.
![image](https://github.com/user-attachments/assets/8aaa7717-1d10-4ac1-94de-cb8a96f79981)
![image](https://github.com/user-attachments/assets/3b4d71c2-517e-4ba3-a6f4-c6d85fbfcd0e)

**Comment by Wildenhaus** [comment]
What file is that? 

I have to recreate the DDS header from the raw data, which means I have to [manually map the format](https://github.com/Wildenhaus/IndexV2/blob/b96b985e22490779add6b0a9fbcefde6e7189664/src/Profiles/Index.Profiles.SpaceMarine2/Jobs/LoadTextureJob.cs#L167). DirectXTex doesn't support every format, so there are probably some incorrect mappings. Not quite sure what to do about that...

**Comment by Nano975** [comment]
The one in that screenshot is "part_muzzle_front_01.pct" 
![part_muzzle_front_01](https://github.com/user-attachments/assets/120d8eeb-0c3f-4957-871c-f00fa9fea1fd)
All the particle textures have the "part_" prefixes

**Comment by Wildenhaus** [comment]
Here's a test where I have XT5 remapped to BC3_UNORM. Seems like it's coming through fine now...
[Index.Profiles.SpaceMarine2.zip](https://github.com/user-attachments/files/17133822/Index.Profiles.SpaceMarine2.zip)

**Comment by Wildenhaus** [comment]
Fixed in [v0.4.0.1](https://github.com/Wildenhaus/IndexV2/releases/tag/v0.4.0.1)
