### ISSUE TITLE
Space Marine 2: Update broke cache file parsing

### ISSUE THREAD

**Issue by Wildenhaus** [Wildenhaus/IndexV2#15]
Saber updated the cache file, breaking the serializer and causing an error on load. They bumped the version to 6 (first int32), the unknown byte after, and added 4 bytes to the end of each entry (CRC?). Have a fix pretty much ready, just needs to be tested.

**Comment by devvz** [comment]
@Wildenhaus i can test if needed

**Comment by Wildenhaus** [comment]
[Index.Profiles.SpaceMarine2.zip](https://github.com/user-attachments/files/17174560/Index.Profiles.SpaceMarine2.zip)
Here's an updated profile. Unfortunately a proper release will have to wait until Monday because I'm on vacation

**Comment by Wildenhaus** [comment]
Fixed in the [v0.4.0.1 hotfix](https://github.com/Wildenhaus/IndexV2/releases/tag/v0.4.0.1-Hotfix)
