### ISSUE TITLE
Space Marine 2 

### ISSUE THREAD

**Issue by VictoriaNice** [Wildenhaus/IndexV2#16]
Hello Wildenhaus, I hope you have a great day/night , 

I do know that a patch broke Space Marine 2 but I installed the first version and still dsnt work, 
I was wondering if i'm doing something wrong ? 

Thx in advance

**Comment by Hati-** [comment]
The 2024-09-26 Space Marine 2 update changed some files which broke this tool. Download the latest IndexV2 release and replace the `./GameProfiles/Index.Profiles.SpaceMarine2.dll` file with the one found in https://github.com/Wildenhaus/IndexV2/issues/15#issuecomment-2380645170 as a quick fix

**Comment by Wildenhaus** [comment]
Fixed in the [v0.4.0.1 hotfix](https://github.com/Wildenhaus/IndexV2/releases/tag/v0.4.0.1-Hotfix)
