### ISSUE TITLE
A request about whether the author can share Star Warriors especially Death Watch stl format files.

### ISSUE THREAD

**Issue by Tangsihan1009** [Wildenhaus/IndexV2#18]
I apologize in advance if my behavior has upset you. I am a warhammer 40k enthusiast from China, and I also want to print the Astarte shape of Space marine II through 3D printing technology. The problem I am facing now is that I don't know what tools or technologies to use to make the materials you provide into stl files to facilitate 3D printing. Therefore, I look forward to you to provide a copy of the stl version of the material file, and I am willing to pay the cost. Here is my email address: 18210409809@163.com    Thank you very much for your reply to me。

**Comment by Wildenhaus** [comment]
Sorry. Reverse engineering file formats is completely acceptable in accordance with United States law, but sharing the game files is not. This tool can extract the files from your copy of the game, but I am legally unable to share any game files with you.
