### ISSUE TITLE
Question: Is Support for Halo 2 Anniversary Multiplayer Possible?

### ISSUE THREAD

**Issue by FurStaku** [Wildenhaus/IndexV2#22]
I noticed that the tool currently only supports content from the Campaign. Would it be possible to extend support to the content from the Multiplayer as well?

**Comment by Wildenhaus** [comment]
Nope, no plans to do so, sorry. H2A Multiplayer uses some frankenstein mashup of the Halo 4 engine - not Saber's engine.

Index was originally designed for Saber Interactive games in mind. V2 of Index was completely rewritten to support any game engine. It is possible for someone to write a GameProfile that supports it, but I don't know enough about the Blam (Halo) engine to get that working as intended.

I think Reclaimer supports it? [The Halo Archive discord](https://discord.com/invite/haloarchive) has successfully extracted assets from MP. I'd check there.
