### ISSUE TITLE
Select a Game Profile

### ISSUE THREAD

**Issue by s3anyboy** [Wildenhaus/IndexV2#5]
Nothing seems available when I open Index, it says select a Game Profile but no profiles are listed, I tried scanning the GameProfiles subfolder but it finds nothing. The Included .dlls are inside the GameProfiles folder but Index does not seem to recognize them? Running as admin or compatibility mode seems to make no difference.

![image](https://github.com/Wildenhaus/IndexV2/assets/65825808/b270c4eb-5ab1-4e0f-9d26-e5af4c25b4c5)

**Comment by Wildenhaus** [comment]
You need to click the + button in the lower left corner and select your game folder. It will populate the game install in the list if it recognizes the folder.
