### ISSUE TITLE
Feature Request: Export multiple assets

### ISSUE THREAD

**Issue by 09williamsad** [Wildenhaus/IndexV2#6]
Version: sm2 wip 93cce19
Priority: Low

Under the current workflow, assets can be exported from IndexV2 one by one.
This is rather tedious when exporting multiple assets.

As a convinience feature in the future, functionality to export multiple assets from the Data Explorer list could be added.
i.e. selecting multiple by Control/Shift clicking or clicking tick boxes, then clicking an export button.

**Comment by Wildenhaus** [comment]
Yeah, that was a feature in the first version of Index, and I intended to include it in this version, but I guess I ran out of time or steam when I released it. I can probably get something set up for this next release.

**Comment by Wildenhaus** [comment]
Added in #8
